name: Android CI/CD

on:
  push:
    branches: 
      - dev_Plugin_OpenApsAIMI_autobuild
  pull_request:
    branches: 
      - dev_Plugin_OpenApsAIMI_autobuild

jobs:
  build-and-sign:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build and Sign Release APK
      env:
        KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        echo "KEYSTORE_FILE=$KEYSTORE_FILE" > keystore.properties
        echo "KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD" >> keystore.properties
        echo "KEY_ALIAS=$KEY_ALIAS" >> keystore.properties
        echo "KEY_PASSWORD=$KEY_PASSWORD" >> keystore.properties
        ./gradlew assembleRelease

    - name: Archive APK
      uses: actions/upload-artifact@v2
      with:
        name: app-full-release.apk
        path: app/build/outputs/apk/release/app-release.apk
    - name: List files in output directory
      run: |
          ls -R app/build/outputs/apk/
